#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(inputs, **req):
    data = {}
    idx = 0
    for x in inputs:
        cnt = data.get(x, 0) + 1
        data[x] = cnt
        if cnt == 1:
            idx += 1
        yield f'{x}\t{idx}\t{cnt}'


if __name__ == '__main__':
    process()
