#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain
import base64


@cgi_entry_plain
def process(inputs, encoding='utf-8', **req):
    for x in inputs:
        raw = base64.b64decode(
            x.replace('-', '+').replace('_', '/') + '=' * (4 - len(x) % 4)
        )
        try:
            yield raw.decode(encoding)
        except:
            yield str(raw)


if __name__ == '__main__':
    process()
