#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(inputs, column=2, sep='\t', **req):
    total = 0
    for x in inputs:
        try:
            total += float(x.split(sep)[column - 1])
        except:
            pass
    for x in inputs:
        x += sep
        try:
            n = float(x.split(sep)[column - 1])
            x += f'{round(n / total * 100, 2)}%'
        except:
            pass
        yield x


if __name__ == '__main__':
    process()
