#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(inputs, filter='', **req):
    filter = filter.replace('｜', '|')
    idx = 1
    data = {}
    for x in inputs:
        if x == '——' or x == '--':
            idx = idx + 1
            continue
        data[x] = data.get(x, [])
        if idx not in data[x]:
            data[x].append(idx)

    for k, v in data.items():
        status = '|'.join(map(str, v))
        if filter == '':
            yield f'{status}\t{k}'
        elif filter == status:
            yield k


if __name__ == '__main__':
    process()
