#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(inputs, num=3, delimiter='\t', **req):
    lines = []
    for x in inputs:
        lines.append(x)
        if len(lines) >= num:
            yield delimiter.join(lines)
            lines.clear()
    if len(lines) > 0:
        yield delimiter.join(lines)


if __name__ == '__main__':
    process()
