#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import *
import json


def flatten_json(y):
    out = {}

    def flatten(x, name=''):
        if type(x) is dict:
            for i in x:
                flatten(x[i], f'{name}_{i}')

        elif type(x) is list:
            for i in range(len(x)):
                flatten(x[i], f'{name}_{i}')

        else:
            out[name[1:]] = x

    flatten(y)
    return out


@cgi_entry_plain
def process(inputs, **req):
    for x in inputs:
        j = json.loads(x)
        yield json.dumps(flatten_json(j), ensure_ascii=False)


if __name__ == '__main__':
    process()
