#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import *
import json
import pandas as pd
import csv
import io


def csv_to_tsv(val):
    outputs = io.StringIO()
    csv.writer(outputs, delimiter='\t', quotechar='\t', quoting=csv.QUOTE_NONE).writerows(
        csv.reader(val.replace('\t', '  ').split('\n')))
    return outputs.getvalue()


def is_json(json_str):
    try:
        json.loads(json_str)
    except ValueError as e:
        return False
    return True


'''
def to_csv(json_str, use_tab=False, **req):
    if use_tab:
        json_str = json_str.replace('\\t', '  ')
    data = pd.read_json(json_str)
    if use_tab:
        return data.to_csv(index=False, sep='\t')
    return data.to_csv(index=False)
'''


def to_csv(json_str, output_type='csv', **req):
    data = pd.read_json(json_str)
    ret = data.to_csv(index=False)
    if output_type == 'table':
        ret = csv_to_tsv(ret)
    return ret


@cgi_entry_plain
def process(input_str, inputs, **req):
    if is_json(input_str):
        yield to_csv(input_str, **req)
    else:
        inputs = [x for x in inputs if is_json(x)]
        yield to_csv(f'[{",".join(inputs)}]',  **req)


if __name__ == '__main__':
    process()
