#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import *
import json

def json_validate(json_str):
    try:
        json.loads(json_str)
    except ValueError as e:
        return str(e)


@cgi_entry_plain
def process(input_str, inputs, **req):
    passed = True
    for i in range(len(inputs)):
        if len(inputs[i]) == 0:
            continue
        err = json_validate(inputs[i])
        if err != None:
            passed = False
            yield f'line {i + 1} error: {err}'
    if passed:
        yield 'passed'

if __name__ == '__main__':
    process()
