#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(inputs, sep='\t', **req):
    data = {}
    for x in inputs:
        l = x.split()
        if len(l) < 2:
            continue
        data[l[0]] = data.get(l[0], [])
        data[l[0]].append(l[1])
    for k, v in data.items():
        yield sep.join([k] + v)


if __name__ == '__main__':
    process()
