#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain
import random


@cgi_entry_plain
def process(inputs, num=100, **req):
    pool = []
    total_weight = 0
    for line in inputs:
        l = line.split()
        if len(l) < 2 or not l[1].isdigit():
            continue
        pool.append((l[0], int(l[1])))
        total_weight += int(l[1])

    for r in random.sample(range(0, total_weight), num if num < total_weight else total_weight):
        for x in pool:
            if r < x[1]:
                yield x[0]
                break
            r -= x[1]


if __name__ == '__main__':
    process()
