#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(input_str, charset='', **req):
    x = input_str
    for r in charset:
        x = x.replace(r, '')
    return x


if __name__ == '__main__':
    process()
