#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(input_str, **req):
    return input_str.replace(req['from'], req['to'])


if __name__ == '__main__':
    process()
