#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

import copy
from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(inputs, mode='csv', column=2, sep='|', **req):
    delimiter = ',' if mode == 'csv' else '\t'
    data = []
    for x in inputs:
        l = x.split(delimiter)
        for i in range(0, len(l)):
            if i + 1 == column:
                for j in l[i].split(sep):
                    if len(j) == 0:
                        continue
                    l[i] = j
                    data.append(copy.deepcopy(l))
    for d in data:
        yield delimiter.join(d)


if __name__ == '__main__':
    process()
