#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(inputs, **req):
    for x in inputs:
        l = x.split()
        if len(l) < 2:
            continue
        l0 = l.pop(0)
        for ln in l:
            yield f'{l0}\t{ln}'


if __name__ == '__main__':
    process()
