#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain
import json


@cgi_entry_plain
def process(inputs, sep='\t', **req):
    sums = []
    for x in inputs:
        cols = x.split(sep)
        for i in range(len(cols)):
            while i >= len(sums):
                sums.append(0)
            try:
                sums[i] += json.loads(cols[i])
            except:
                pass
    return sep.join(map(str, sums))


if __name__ == '__main__':
    process()
