#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain
from datetime import datetime
import time


def parse(x):
    try:
        ts = int(x)
        if int(ts / 1E12) == 1:
            ts = int(ts / 1000)

        now = time.time()
        year = 86400 * 365
        if ts < now - year or ts > now + year:
            return x

        return str(datetime.fromtimestamp(ts))

    except:
        return x


@cgi_entry_plain
def process(inputs, sep='\t', **req):
    for x in inputs:
        yield sep.join([parse(i) for i in x.split(sep)])


if __name__ == '__main__':
    process()
