#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import cgi_entry_plain


@cgi_entry_plain
def process(inputs, **req):
    s = set()
    for x in inputs:
        if not x in s:
            yield x
        s.add(x)


if __name__ == '__main__':
    process()
