#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import *
from urllib.parse import quote


@cgi_entry_plain
def process(input_str, inputs, mode='line', safe='', **req):
    if mode == 'all':
        yield quote(input_str, safe=safe)
    else:
        for x in inputs:
            yield quote(x, safe=safe)


if __name__ == '__main__':
    process()
