#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from lib.taro_comm import *
from urllib.parse import unquote


@cgi_entry_plain
def process(inputs, **req):
    for x in inputs:
        yield unquote(x)


if __name__ == '__main__':
    process()
