title = "json转csv"
desc = "json转成csv，支持一整个json，或者每行一个json"
output_file = "from_json.csv"

[[options]]
key = "output_type"
title = "输出格式"

[[options.list]]
title = "csv（逗号分隔）"
value = "csv"

[[options.list]]
title = "表格（tab分割）"
value = "table"

[[example]]
url = "#?output_type=csv&input=%7B%22a%22%3A1%2C%22b%22%3A%22A%22%7D%0A%7B%22a%22%3A2%2C%22b%22%3A%22B%22%7D%0A%7B%22a%22%3A3%2C%22b%22%3A%22C%22%7D"
