title = "列拆分成多行"

[[options]]
key = "column"
title = "列编号"
default = 2

[[options]]
key = "mode"
title = "格式"

[[options.list]]
title = "表格（tab分隔）"
value = "table"

[[options.list]]
title = "csv"
value = "csv"

[[options]]
key = "sep"
title = "分隔符"
default = "|"

[[example]]
url = "#?column=2&mode=table&sep=%7C&input=1%09a%7Cb%7Cc%0A2%09d%7Ce"
